// Local implementation to avoid DLight import issues
export function createMockWebGL2Context() {
  const calls: string[] = [];

  return {
    calls,
    viewport: vi.fn(),
    clearColor: vi.fn(),
    clear: vi.fn(),
    enable: vi.fn(),
    disable: vi.fn(),
    depthFunc: vi.fn(),
    cullFace: vi.fn(),
    depthMask: vi.fn(),
    blendFuncSeparate: vi.fn(),
    blendFunc: vi.fn(),
    getExtension: vi.fn(() => ({})),
    createShader: vi.fn(() => ({})),
    shaderSource: vi.fn(),
    compileShader: vi.fn(),
    getShaderParameter: vi.fn(() => true),
    getShaderInfoLog: vi.fn(() => ''),
    deleteShader: vi.fn(),
    createProgram: vi.fn(() => ({})),
    attachShader: vi.fn(),
    bindAttribLocation: vi.fn(),
    linkProgram: vi.fn(),
    getProgramParameter: vi.fn(() => true),
    getProgramInfoLog: vi.fn(() => ''),
    deleteProgram: vi.fn(),
    useProgram: vi.fn(),
    getUniformLocation: vi.fn(() => ({})),
    getAttribLocation: vi.fn(() => 0),
    createBuffer: vi.fn(() => ({})),
    bindBuffer: vi.fn(),
    bufferData: vi.fn(),
    bufferSubData: vi.fn(),
    deleteBuffer: vi.fn(),
    createVertexArray: vi.fn(() => ({})),
    bindVertexArray: vi.fn(),
    enableVertexAttribArray: vi.fn(),
    vertexAttribPointer: vi.fn(),
    vertexAttribDivisor: vi.fn(),
    deleteVertexArray: vi.fn(),
    createTexture: vi.fn(() => ({})),
    activeTexture: vi.fn(),
    bindTexture: vi.fn(),
    texParameteri: vi.fn(),
    texImage2D: vi.fn(),
    deleteTexture: vi.fn(),
    createFramebuffer: vi.fn(() => ({})),
    bindFramebuffer: vi.fn(),
    framebufferTexture2D: vi.fn(),
    deleteFramebuffer: vi.fn(),
    checkFramebufferStatus: vi.fn(() => 36053), // GL_FRAMEBUFFER_COMPLETE
    createRenderbuffer: vi.fn(() => ({})),
    bindRenderbuffer: vi.fn(),
    renderbufferStorage: vi.fn(),
    framebufferRenderbuffer: vi.fn(),
    deleteRenderbuffer: vi.fn(),
    drawArrays: vi.fn(),
    drawElements: vi.fn(),
    uniform1f: vi.fn(),
    uniform1i: vi.fn(),
    uniform4f: vi.fn(),
    uniform3fv: vi.fn(),
    uniform3f: vi.fn(),
    uniform2f: vi.fn(),
    uniform4fv: vi.fn(),
    uniformMatrix4fv: vi.fn(),
    // Constants
    COMPILE_STATUS: 0,
    LINK_STATUS: 0,
    VERTEX_SHADER: 0,
    FRAGMENT_SHADER: 0,
    ARRAY_BUFFER: 0,
    ELEMENT_ARRAY_BUFFER: 0,
    STATIC_DRAW: 0,
    DYNAMIC_DRAW: 0,
    TEXTURE_2D: 0,
    TEXTURE0: 0,
    RGBA: 0,
    UNSIGNED_BYTE: 0,
    NEAREST: 0,
    LINEAR: 0,
    CLAMP_TO_EDGE: 0,
    COLOR_BUFFER_BIT: 0,
    DEPTH_BUFFER_BIT: 0,
    TRIANGLES: 0,
    UNSIGNED_SHORT: 0,
    CULL_FACE: 0,
    DEPTH_TEST: 1,
    FRAMEBUFFER: 0,
    FRAMEBUFFER_COMPLETE: 36053,
  };
}
